const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('electron', {
  getComputerName: () => ipcRenderer.invoke('get-computer-name'),
  checkWifi: () => ipcRenderer.invoke('check-wifi'),
  isElectron: true,
  serialport: {
    list: () => ipcRenderer.invoke('serialport:list'),
    open: (portPath, baudRate) => ipcRenderer.invoke('serialport:open', portPath, baudRate),
    write: (data) => ipcRenderer.invoke('serialport:write', data),
    read: (length) => ipcRenderer.invoke('serialport:read', length),
    peek: (length) => ipcRenderer.invoke('serialport:peek', length),
    isOpen: () => ipcRenderer.invoke('serialport:is-open'),
    close: () => ipcRenderer.invoke('serialport:close'),
  },
  config: {
    load: () => ipcRenderer.invoke('config:load'),
    save: (config) => ipcRenderer.invoke('config:save', config),
    getPath: () => ipcRenderer.invoke('config:get-path'),
  },
  games: {
    getFolderPath: () => ipcRenderer.invoke('games:get-folder-path'),
    list: () => ipcRenderer.invoke('games:list'),
    readFile: (gameId, filename) => ipcRenderer.invoke('games:read-file', gameId, filename),
    writeFile: (gameId, filename, content, isBinary) => ipcRenderer.invoke('games:write-file', gameId, filename, content, isBinary),
    getMediaPath: (gameId, filename) => ipcRenderer.invoke('games:get-media-path', gameId, filename),
    listMediaFolder: (gameId, folderId) => ipcRenderer.invoke('games:list-media-folder', gameId, folderId),
  },
  db: {
    connect: () => ipcRenderer.invoke('db:connect'),
    testConnection: (url) => ipcRenderer.invoke('db:testConnection', url),
    query: (sql, params) => ipcRenderer.invoke('db:query', sql, params),
  },
  clients: {
    load: () => ipcRenderer.invoke('clients:load'),
    saveSelected: (clientData) => ipcRenderer.invoke('clients:save-selected', clientData),
    loadSelected: () => ipcRenderer.invoke('clients:load-selected'),
  },
  cards: {
    getLocalVersion: () => ipcRenderer.invoke('cards:get-local-version'),
    saveFile: (version, content) => ipcRenderer.invoke('cards:save-file', version, content),
    saveOnDemandFile: (content) => ipcRenderer.invoke('cards:save-on-demand-file', content),
  },
  patterns: {
    listFolders: (gameTypeName) => ipcRenderer.invoke('patterns:list-folders', gameTypeName),
    readFile: (gameTypeName, patternName, fileName) => ipcRenderer.invoke('patterns:read-file', gameTypeName, patternName, fileName),
    getLocalVersions: (gameType, patternSlug) => ipcRenderer.invoke('patterns:get-local-versions', gameType, patternSlug),
    saveFile: (gameType, patternSlug, version, content, isUserPattern) => ipcRenderer.invoke('patterns:save-file', gameType, patternSlug, version, content, isUserPattern),
  },
  layouts: {
    getLocalVersions: (gameType) => ipcRenderer.invoke('layouts:get-local-versions', gameType),
    readFile: (gameType) => ipcRenderer.invoke('layouts:read-file', gameType),
    saveFile: (gameType, version, content) => ipcRenderer.invoke('layouts:save-file', gameType, version, content),
  },
  scenarios: {
    getFolderPath: () => ipcRenderer.invoke('scenarios:get-folder-path'),
    load: () => ipcRenderer.invoke('scenarios:load'),
    saveGameData: (uniqid, gameData) => ipcRenderer.invoke('scenarios:save-game-data', uniqid, gameData),
    saveCsv: (uniqid, filename, content) => ipcRenderer.invoke('scenarios:save-csv', uniqid, filename, content),
    saveMedia: (uniqid, folder, filename, base64Data) => ipcRenderer.invoke('scenarios:save-media', uniqid, folder, filename, base64Data),
    refresh: () => ipcRenderer.invoke('scenarios:refresh'),
    delete: (uniqid) => ipcRenderer.invoke('scenarios:delete', uniqid),
    getImage: (uniqid) => ipcRenderer.invoke('scenarios:get-image', uniqid),
    getLocalVersions: () => ipcRenderer.invoke('scenarios:get-local-versions'),
    getFolderStructure: () => ipcRenderer.invoke('scenarios:get-folder-structure'),
    getStorageInfo: () => ipcRenderer.invoke('scenarios:get-storage-info'),
    deletePath: (itemPath) => ipcRenderer.invoke('scenarios:delete-path', itemPath),
  },
  apiLogs: {
    write: (logData) => ipcRenderer.invoke('api-logs:write', logData),
    read: () => ipcRenderer.invoke('api-logs:read'),
    clear: () => ipcRenderer.invoke('api-logs:clear'),
  },
  system: {
    openDataFolder: () => ipcRenderer.invoke('system:open-data-folder'),
    setAutoLaunch: (enable) => ipcRenderer.invoke('system:set-auto-launch', enable),
    getAutoLaunch: () => ipcRenderer.invoke('system:get-auto-launch'),
  },
  setAutoLaunch: (enable) => ipcRenderer.invoke('system:set-auto-launch', enable),
});
